# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-26 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('travel_from', models.CharField(max_length=255)),
                ('travel_to', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joined_by', models.ManyToManyField(related_name='joined_trips', to='user_login_app.User')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_trips', to='user_login_app.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='quote',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='uploader',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
